In [5]:
import datasets as ds
import numpy as np
from numpy import array
import tensorflow
import keras
import pandas as pd
from keras.preprocessing.text import one_hot
from keras_preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [6]:
dir(ds)

['Array2D',
 'Array3D',
 'Array4D',
 'Array5D',
 'ArrowBasedBuilder',
 'Audio',
 'AutomaticSpeechRecognition',
 'BeamBasedBuilder',
 'BuilderConfig',
 'ClassLabel',
 'Dataset',
 'DatasetBuilder',
 'DatasetDict',
 'DatasetInfo',
 'DownloadConfig',
 'DownloadManager',
 'DownloadMode',
 'Features',
 'GeneratorBasedBuilder',
 'Image',
 'ImageClassification',
 'IterableDataset',
 'IterableDatasetDict',
 'LanguageModeling',
 'Metric',
 'MetricInfo',
 'NamedSplit',
 'NamedSplitAll',
 'QuestionAnsweringExtractive',
 'ReadInstruction',
 'SCRIPTS_VERSION',
 'Sequence',
 'Split',
 'SplitBase',
 'SplitDict',
 'SplitGenerator',
 'SplitInfo',
 'StreamingDownloadManager',
 'SubSplitInfo',
 'Summarization',
 'TaskTemplate',
 'TextClassification',
 'Translation',
 'TranslationVariableLanguages',
 'Value',
 'Version',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'arrow_dataset',
 'arrow_reader',
 'arrow_wr

In [7]:
ds.list_datasets()

['acronym_identification',
 'ade_corpus_v2',
 'adversarial_qa',
 'aeslc',
 'afrikaans_ner_corpus',
 'ag_news',
 'ai2_arc',
 'air_dialogue',
 'ajgt_twitter_ar',
 'allegro_reviews',
 'allocine',
 'alt',
 'amazon_polarity',
 'amazon_reviews_multi',
 'amazon_us_reviews',
 'ambig_qa',
 'americas_nli',
 'ami',
 'amttl',
 'anli',
 'app_reviews',
 'aqua_rat',
 'aquamuse',
 'ar_cov19',
 'ar_res_reviews',
 'ar_sarcasm',
 'arabic_billion_words',
 'arabic_pos_dialect',
 'arabic_speech_corpus',
 'arcd',
 'arsentd_lev',
 'art',
 'arxiv_dataset',
 'ascent_kb',
 'aslg_pc12',
 'asnq',
 'asset',
 'assin',
 'assin2',
 'atomic',
 'autshumato',
 'babi_qa',
 'banking77',
 'bbaw_egyptian',
 'bbc_hindi_nli',
 'bc2gm_corpus',
 'beans',
 'best2009',
 'bianet',
 'bible_para',
 'big_patent',
 'billsum',
 'bing_coronavirus_query_set',
 'biomrc',
 'biosses',
 'blbooks',
 'blbooksgenre',
 'blended_skill_talk',
 'blimp',
 'blog_authorship_corpus',
 'bn_hate_speech',
 'bnl_newspapers',
 'bookcorpus',
 'bookcorpusopen'

In [8]:
len(ds.list_datasets())

8690

In [10]:
cola_dataset = ds.load_dataset('glue', 'cola', split = 'train')

Reusing dataset glue (C:\Users\hp\.cache\huggingface\datasets\glue\cola\1.0.0\dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)


In [11]:
qqp_dataset = ds.load_dataset('glue', 'qqp', split = 'train')

Reusing dataset glue (C:\Users\hp\.cache\huggingface\datasets\glue\qqp\1.0.0\dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)


In [12]:
qqp_dataset.features

{'question1': Value(dtype='string', id=None),
 'question2': Value(dtype='string', id=None),
 'label': ClassLabel(num_classes=2, names=['not_duplicate', 'duplicate'], id=None),
 'idx': Value(dtype='int32', id=None)}

In [13]:
qqp_dataset.num_rows

363846

In [14]:
qqp_dataset.num_columns

4

In [15]:
qqp_dataset.shape

(363846, 4)

In [16]:
type(qqp_dataset)

datasets.arrow_dataset.Dataset

In [17]:
qqp_dataset.info

DatasetInfo(description='GLUE, the General Language Understanding Evaluation benchmark\n(https://gluebenchmark.com/) is a collection of resources for training,\nevaluating, and analyzing natural language understanding systems.\n\n', citation='@online{WinNT,\n  author = {Iyer, Shankar and Dandekar, Nikhil and Csernai, Kornel},\n  title = {First Quora Dataset Release: Question Pairs},\n  year = {2017},\n  url = {https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs},\n  urldate = {2019-04-03}\n}\n@inproceedings{wang2019glue,\n  title={{GLUE}: A Multi-Task Benchmark and Analysis Platform for Natural Language Understanding},\n  author={Wang, Alex and Singh, Amanpreet and Michael, Julian and Hill, Felix and Levy, Omer and Bowman, Samuel R.},\n  note={In the Proceedings of ICLR.},\n  year={2019}\n}\n', homepage='https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs', license='', features={'question1': Value(dtype='string', id=None), 'question2': Value(dtype='string', 

In [18]:
qqp_dataset.description

'GLUE, the General Language Understanding Evaluation benchmark\n(https://gluebenchmark.com/) is a collection of resources for training,\nevaluating, and analyzing natural language understanding systems.\n\n'

In [19]:
qqp_dataset.citation

'@online{WinNT,\n  author = {Iyer, Shankar and Dandekar, Nikhil and Csernai, Kornel},\n  title = {First Quora Dataset Release: Question Pairs},\n  year = {2017},\n  url = {https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs},\n  urldate = {2019-04-03}\n}\n@inproceedings{wang2019glue,\n  title={{GLUE}: A Multi-Task Benchmark and Analysis Platform for Natural Language Understanding},\n  author={Wang, Alex and Singh, Amanpreet and Michael, Julian and Hill, Felix and Levy, Omer and Bowman, Samuel R.},\n  note={In the Proceedings of ICLR.},\n  year={2019}\n}\n'

In [20]:
qqp_dataset.license

''

In [21]:
qqp_dataset.homepage

'https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs'

In [22]:
qqp_dataset.data

MemoryMappedTable
question1: string
question2: string
label: int64
idx: int32
----
question1: [["How is the life of a math student? Could you describe your own experiences?","How do I control my horny emotions?","What causes stool color to change to yellow?","What can one do after MBBS?","Where can I find a power outlet for my laptop at Melbourne Airport?",...,"What is meant by surgical strike?","How do I prepare for TOEFL or IELTS?","Did indian muslim support pakistan in 1971 war? Where are evidences if yes?","What is the real world example of waterfall model regarding software?","Why can the US impose economic sanctions on other countries?"],["How can I make money using Tumblr?","I'm 24 years old and still having regular pimples on my face and back. How can I to reduce them? What are all the reasons for this?","Has anyone experienced pervasive, often debilitating fatigue from coming off Lithium and/or Olanzapine and if so, for how long?","There is a quote in the movie The Imitation G

In [23]:
qqp_dataset.column_names

['question1', 'question2', 'label', 'idx']

In [30]:
print(len(qqp_dataset['question1']))

363846


In [24]:
qqp_dataset[:10]

{'question1': ['How is the life of a math student? Could you describe your own experiences?',
  'How do I control my horny emotions?',
  'What causes stool color to change to yellow?',
  'What can one do after MBBS?',
  'Where can I find a power outlet for my laptop at Melbourne Airport?',
  "How not to feel guilty since I am Muslim and I'm conscious we won't have sex together?",
  'How is air traffic controlled?',
  'What is the best self help book you have read? Why? How did it change your life?',
  "Can I enter University of Melbourne if I couldn't achieve the guaranteed marks in Trinity College Foundation?",
  'Do you need a passport to go to Jamaica from the United States?'],
 'question2': ['Which level of prepration is enough for the exam jlpt5?',
  'How do you control your horniness?',
  'What can cause stool to come out as little balls?',
  'What do i do after my MBBS ?',
  'Would a second airport in Sydney, Australia be needed if a high-speed rail link was created between Melb

In [25]:
qqp_df = qqp_dataset.to_pandas()

In [53]:
qqp_df.head(20)

question1  \
0   How is the life of a math student? Could you d...   
1                 How do I control my horny emotions?   
2        What causes stool color to change to yellow?   
3                         What can one do after MBBS?   
4   Where can I find a power outlet for my laptop ...   
5   How not to feel guilty since I am Muslim and I...   
6                      How is air traffic controlled?   
7   What is the best self help book you have read?...   
8   Can I enter University of Melbourne if I could...   
9   Do you need a passport to go to Jamaica from t...   
10  What is the district of Edgware and how does t...   
11  What will be Hillary Clinton's policy towards ...   
12    What is the responsibility of SAP ERP key user?   
13  Which is the best book to study TENSOR for gen...   
14  How is being gay or lesbian less moral than di...   
15         How do you thank a Disneyland cast member?   
16  What are the coolest Android hacks and tricks ...   
17  If you received a check from Donald Knuth, wha...   
18            Which are the best motivational videos?   
19                         How do I lose weight fast?   

                                            question2  label  idx  
0   Which level of prepration is enough for the ex...      0    0  
1                  How do you control your horniness?      1    1  
2   What can cause stool to come out as little balls?      0    2  
3                        What do i do after my MBBS ?      1    3  
4   Would a second airport in Sydney, Australia be...      0    4  
5   I don't beleive I am bulimic, but I force thro...      0    5  
6        How do you become an air traffic controller?      0    6  
7     What are the top self help books I should read?      1    7  
8   University of the Philippines: If I take a sec...      0    8  
9                          How can I move to Jamaica?      0    9  
10  What is the county of Edgware and how does the...      0   10  
11  What will be Hilary Clinton's policy towards I...      1   11  
12              What is a qualified SAP ERP key user?      0   12  
13        Which is the best book for tensor calculus?      1   13  
14  "Why do a lot of theists and agnostics confuse...      0   14  
15      How can I go to Disneyland with little money?      0   15  
16       What are some cool hacks for Android phones?      1   16  
17                    How can I contact Donald Knuth?      0   17  
18      What are some of the best motivational clips?      1   18  
19        What is the best way to reduce weight fast?      1   19

In [28]:
start_search = qqp_dataset.filter(lambda x: x['question1'].startswith('Would'))
print(len(start_search['question1']))

Loading cached processed dataset at C:\Users\hp\.cache\huggingface\datasets\glue\qqp\1.0.0\dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad\cache-743f74bb7b296433.arrow


930


In [31]:
qqp_df.to_csv("qqp_dataset")

In [36]:
df_qqp = qqp_df.head(100)
df_qqp.to_csv("df_qqp")

In [38]:
# encoded each word in a question...
dim_size = 100
encode = [one_hot(i, dim_size) for i in df_qqp['question1']]
print(encode)

[[83, 49, 61, 75, 90, 44, 43, 62, 14, 86, 81, 85, 79, 44], [83, 46, 85, 31, 59, 57, 16], [32, 50, 62, 32, 43, 85, 43, 33], [32, 62, 26, 46, 50, 86], [15, 62, 85, 30, 44, 97, 10, 20, 59, 24, 46, 30, 65], [83, 7, 43, 75, 8, 51, 85, 11, 48, 66, 73, 19, 54, 64, 65, 34, 1], [83, 49, 25, 93, 61], [32, 49, 61, 28, 24, 40, 52, 86, 65, 45, 8, 83, 97, 15, 85, 85, 75], [62, 85, 26, 64, 90, 30, 66, 85, 29, 5, 61, 67, 38, 5, 94, 84, 94], [46, 86, 54, 44, 18, 43, 20, 43, 91, 96, 61, 29, 12], [32, 49, 61, 79, 90, 81, 66, 83, 95, 61, 80, 77, 43, 61, 25, 19, 90, 52], [32, 46, 48, 64, 85, 14, 14, 45, 66, 15, 51, 22], [32, 49, 61, 15, 90, 31, 31, 14, 87], [35, 49, 61, 28, 52, 43, 34, 88, 20, 61, 49, 96, 1], [83, 49, 89, 85, 83, 91, 61, 94, 94, 52], [83, 46, 86, 24, 44, 81, 46, 24], [32, 6, 61, 84, 89, 99, 66, 94, 86, 38], [66, 86, 81, 44, 84, 96, 85, 7, 32, 97, 86, 46, 66, 8, 97, 86, 62, 15], [35, 6, 61, 28, 98, 83], [83, 46, 85, 40, 13, 27], [66, 44, 56, 49, 41, 32, 49, 61, 23, 33, 61, 24, 49, 52, 94, 3

In [42]:
# vector size should be same
max_length = max([len(i) for i in encode])
vector_trimming = pad_sequences(encode, maxlen = max_length, padding = 'pre')
print(vector_trimming)

[[ 0  0  0 ... 85 79 44]
 [ 0  0  0 ... 59 57 16]
 [ 0  0  0 ... 85 43 33]
 ...
 [ 0  0  0 ... 66 13 45]
 [ 0  0  0 ...  5 73 23]
 [ 0  0  0 ... 37 90 12]]


In [43]:
# Model Building - Word Embedding
model_build = Sequential()
model_build.add(Embedding(dim_size, 10, input_length = max_length))
model_build.add(Flatten())
model_build.add(Dense(1, activation = 'sigmoid'))

In [44]:
model_build.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [52]:
model_build.fit(vector_trimming, df_qqp['label'], epochs = 30)

loss_function, accuracy_metrics = model_build.evaluate(vector_trimming, df_qqp['label'], verbose = 0)
print("\n Accuracy:", accuracy_metrics*100, "%")

Epoch 1/30
4/4 [==============================] - 0s 2ms/step - loss: 0.0936 - accuracy: 1.0000
Epoch 2/30
4/4 [==============================] - 0s 4ms/step - loss: 0.0923 - accuracy: 1.0000
Epoch 3/30
4/4 [==============================] - 0s 4ms/step - loss: 0.0908 - accuracy: 1.0000
Epoch 4/30
4/4 [==============================] - 0s 3ms/step - loss: 0.0895 - accuracy: 1.0000
Epoch 5/30
4/4 [==============================] - 0s 3ms/step - loss: 0.0881 - accuracy: 1.0000
Epoch 6/30
4/4 [==============================] - 0s 4ms/step - loss: 0.0869 - accuracy: 1.0000
Epoch 7/30
4/4 [==============================] - 0s 3ms/step - loss: 0.0855 - accuracy: 1.0000
Epoch 8/30
4/4 [==============================] - 0s 3ms/step - loss: 0.0842 - accuracy: 1.0000
Epoch 9/30
4/4 [==============================] - 0s 3ms/step - loss: 0.0830 - accuracy: 1.0000
Epoch 10/30
4/4 [==============================] - 0s 3ms/step - loss: 0.0818 - accuracy: 1.0000
Epoch 11/30
4/4 [======================

In [88]:
# Prediction
user_sentences = ["How to play this game?", "Do you feel happy today?", 
                 "What is bibliography?", "What is an anode?"]

dim_size_pre = 100
encode_pre = [one_hot(i, dim_size_pre) for i in user_sentences]
print(encode_pre)

[[83, 43, 35, 53, 4], [46, 86, 75, 96, 47], [32, 49, 37], [32, 49, 44, 92]]


In [89]:
max_length_pre = 33
vector_trimming_pre = pad_sequences(encode_pre, maxlen = max_length_pre, padding = 'pre')
print(vector_trimming_pre)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0 83 43 35 53  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0 46 86 75 96 47]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0 32 49 37]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0 32 49 44 92]]


In [90]:
prediction = model_build.predict(vector_trimming_pre) # --- Probability
#prediction_execute = np.argmax(prediction, axis = 1)
print(prediction)
#print(prediction_execution)
predictions = (model_build.predict(vector_trimming_pre) > 0.5).astype("int32")
print(predictions)

1/1 [==============================] - 0s 18ms/step
[[0.6812705 ]
 [0.44142613]
 [0.19323798]
 [0.26917392]]
1/1 [==============================] - 0s 17ms/step
[[1]
 [0]
 [0]
 [0]]
